### ISSUE TITLE
i had error to open this project

### ISSUE THREAD

**Issue by Nyxvigi** [coder-rukon/Hospital-Management-System-php-project#2]
A PHP Error was encountered
Severity: Warning

Message: file_get_contents(http://localhost/hospital/Ajax_query/get_coutry/BD): Failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found

Filename: helpers/functions_helper.php

Line Number: 36

Backtrace:

File: C:\xampp\htdocs\Hospital-Management-System-php-project-master\application\helpers\functions_helper.php
Line: 36
Function: file_get_contents

File: C:\xampp\htdocs\Hospital-Management-System-php-project-master\application\views\page\doctors.php
Line: 85
Function: get_country

File: C:\xampp\htdocs\Hospital-Management-System-php-project-master\application\controllers\Welcome.php
Line: 13
Function: view

File: C:\xampp\htdocs\Hospital-Management-System-php-project-master\index.php
Line: 315
Function: require_once

**Comment by coder-rukon** [comment]
I think listed file are missing. Please have a look. 
files/country/capital.json
files/country/currency.json
files/country/names.json
files/country/phone.json

https://github.com/coder-rukon/Hospital-Management-System-php-project/tree/master/files/country

**Comment by Nyxvigi** [comment]
the file is already there. im using xamp btw

**Comment by coder-rukon** [comment]
Does .htaccess file exist in your root directory ?
[htaccess](https://github.com/coder-rukon/Hospital-Management-System-php-project/blob/master/.htaccess)

**Comment by Nyxvigi** [comment]
yes sir.

**Comment by coder-rukon** [comment]
Please rename your project directory Hospital-Management-System-php-project-master to hospital 
So your project url should be http://localhost/hospital

**Comment by Nyxvigi** [comment]
tq sir
